import os

DEFAULT_TOKEN_EXPIRE_SECONDS = 86400
MAX_TOKEN_EXPIRE_SECONDS = 86400

ROLE_PUBLISHER = 1
ROLE_SUBSCRIBER = 2

MISSED_TIMEOUT_SECONDS = 60

# Local recording service URL
RECORDER_SERVICE_URL = os.environ.get("RECORDER_SERVICE_URL", "http://localhost:3100")
